project:
  type: website
  output-dir: docs

website:
  title: "Baltimore City Canid Project"
  navbar:
    left:
      - text: "About the Project"
        href: index.qmd
      - text: "Meet the Scientists"
        href: bio.qmd
      - text: "Report Canid Sightings"
        href: report.qmd

format:
  html:
    theme: cosmo
    css: styles.css