project:
  type: website
  output-dir: docs

website:
  title: "Baltimore City Canid Project"
  navbar:
    logo: images/BCCanidProject_Logo.png
    left:
      - text: "About the Project"
        href: index.qmd
      - text: "Meet the Scientists"
        href: bio.qmd
      - text: "Report Canid Sightings"
        href: report.qmd
  page-footer:
    center: "© Baltimore City Canid Project | Towson University"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false